### PR TITLE
Prepare 8.0a2 cylc metapackage release

### PR DESCRIPTION
**Pull request by kinow**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kinow** [comment]
It won't be able to build due to the pending cylc ui server PR: https://github.com/conda-forge/cylc-uiserver-feedstock/pull/4

But once build passes, we just need to remember to re-render it, and then should be ready to be reviewed/merged.

**Comment by oliver-sanders** [comment]
Poked tests...

**Comment by kinow** [comment]
> Poked tests...



> Poked tests...

Thanks!

image

It may take a few minutes/hours (not days, hopefully) for the build to pass. Not sure whether it's the actual conda server replying that the version is not found, or if the client/vm-or-container that has some cache. Yesterday the same happened when building cylc-uiserver after cylc-flow was released.

**Comment by kinow** [comment]
Hmm, now it found all the software dependencies, `cylc-ui`, `cylc-uiserver`, `cylc-flow`, etc. But getting an `ImportError` for some `extensionmethod from rx.internal` 🤔

**Comment by kinow** [comment]
Built it locally, got the same error. Inspecting the dependency tree. Looks like we have some issue with version ranges in the conda recipe.

Conda:

- `rx:                      3.1.1-py_0              conda-forge`-

pip:

- `Rx                  1.6.1`

And looking at `pipdeptree` for working setuptools/pip setup:

image

So something with `graphene` or `graphene-tornado` versions.

**Comment by kinow** [comment]
Hmm, funny. Installing `cylc-uiserver` individually in the same conda environment:

image

That appears to be respecting cylc-uiserver's version ranges

```
- graphene-tornado >=2.6
- graphql-core <3,>=2.1
```

**Comment by kinow** [comment]
We are using an older version of [`graphql-core`](https://github.com/graphql-python/graphql-core/). At the moment I'm getting 2.2 in Conda. There are tags in that repository for 1.x, and for 3.x release series. Looks like they didn't use tags for the 2.x series.

Their conda repository has a [branch 2.x](https://github.com/conda-forge/graphql-core-feedstock/blob/6516f430525d794be120861d93ea2ef3981a8846/recipe/meta.yaml#L26) for 2.3.2, where rx is correctly set to <2

image

We are using `graphql-core 2.2` :thinking: 

image

I think I found now the reason. Looking at the past commits in `conda-forge/graphql-core-feedstock`, looks like in `2.2` of `graphql-core`, they used the range `rx >=1.6.0`. The `<2` constraint was added in a later release.

Which means we are getting 3.x as that's true for `rx >= 1.6.0`. Now just need to think how to solve that in our recipes. Probably will need to cut a new release of - at least - cylc-uiserver (release in conda, increasing build-number, won't touch PYPI)

image

**Comment by kinow** [comment]
Building everything locally to test the changes for `rx`. Just tried the final command `conda install cylc==8.0a2 --use-local`, but got an error due to python 3.8 :thinking: 

`- cylc==8.0a2 -> python[version='>=3.7,<3.8.0a0']`

Not sure where we are defining we don't want Python 3.8.

**Comment by kinow** [comment]
After much troubleshooting, and re-building packages (which takes some minutes) decided to delete everything and create a new Conda environment. It worked with the changes for `rx` :pray: 

I decided to do that, as I realized I had Python 3.7 on this VM. But for some reason Conda was saying I had `python==3.8` :confused: 

Will prepare the PR's for cylc-flow and cylc-uiserver.

image

The screenshot above has Cylc 8.0a2 running, after building cylc-uiserver and cylc-flow locally, then building and installing cylc metapackage with the `--use-local` and confirming it used my newly built versions for uis & flow.

**Comment by kinow** [comment]
Finished testing this recipe, with the current PR's in cylc-ui-feedstock, cylc-flow-feedstock, and cylc-uiserver-feedstock.

If someone else would like to try it:

- Check out all the branches
- Go to the leaf projects first (e.g. visit ui / flow / uiserver / cylc metapackage in order)
- Build each project as you visit it `conda-build ./recipe`
- When you finish building cylc metapackage, install everything with `conda install --use-local --force-reinstall --verbose cylc==8.0a2` (you may want to activate some conda env first to undo it later)

There will be confirmation screen, where you can verify that the installed ui/flow/uis/etc packages are coming from your local computer, not from conda-forge. Also check the `rx` library version. It must be 1.x, not latest 3.x (see threads from today for more on our repos here and Element chat)

Then follow the 8.0a2 release notes, executing that long `jupyterhub --blablabla` command line.

You should now be able to run workflows, and use the UI :+1: (and finish reviewing :grimacing: )

**Comment by kinow** [comment]
Now we just need to wait a few minutes/hours, then re-trigger CI. If that passes, re-render recipe (bot does that for us), and then it will be one click away from releasing Cylc 8.0a2 :tada:

**Comment by kinow** [comment]
@conda-forge-admin, please rerender

**Review by oliver-sanders — APPROVED** [review]

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
