### PR TITLE
modified for rc1

### PR DESCRIPTION
**Pull request by wxtim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wxtim** [comment]
@conda-forge-admin, please rerender

**Comment by wxtim** [comment]
@conda-forge-admin, please rerender

**Review by oliver-sanders — CHANGES_REQUESTED** [review]
This feedstock is deprecated.

The cylc-admin release issue outlines all the packages which need release - https://github.com/cylc/cylc-admin/issues/144

**Comment by oliver-sanders** [comment]
https://github.com/cylc/cylc-admin/issues/130#issuecomment-966519340

**Pull request closed without merging**
